### PR TITLE
Fix broken URL's

### LINKED ISSUE #3: misspelled URLs

### PR DESCRIPTION
**Pull request by kerrtravers**
Fixes #3

### CODE REVIEW

**Comment by Narulacodes** [comment]
The Travis Build is failing

**Review by radioblahaj — CHANGES_REQUESTED** [review]
Travis Build is failing.

**Comment by kerrtravers** [comment]
That's because you haven't set up TravisCI for this project:

> Could not find .travis.yml, using standard configuration.

...and it's only a simple URL change.

**Comment by radioblahaj** [comment]
Opps, Didn't notice that.

**Review by radioblahaj — APPROVED** [review]
LGTM
PRG|TM

**Comment by kerrtravers** [comment]
@Narulacodes When will this be merged?

**Comment by AmazingMech2418** [comment]
:)

**Pull request merged**
